# Generated by Django 4.0.6 on 2022-07-22 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_jobstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobstatus',
            name='job_post',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.jobstatus'),
        ),
    ]
