# Generated by Django 4.0.6 on 2022-07-22 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_jobstatus_job_post_jobpost_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'job_post_progress',
            },
        ),
        migrations.AddField(
            model_name='jobpost',
            name='progress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.jobprogress'),
        ),
    ]
